name: Build the app

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '0 0 15 * *'

jobs:
  
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: ./gradlew test --stacktrace  
  
  build:
    name: Build and Deploy Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt Firebase Config
      run: ./.github/scripts/decrypt.sh
      env:
        FIREBASE_SERVICE: ${{secrets.FIREBASE_SERVICE}}
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build 
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Note
        path: apk/Note.apk
    
