name: Build the app

on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '0 0 15 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Decrypt Firebase Config
      run: cat "$FIREBASE_SERVICE"
      env:
        FIREBASE_SERVICE: ${{secrets.FIREBASE_SERVICE}}
    
